# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'

      - name: Checkout Repo
        uses: actions/checkout@v2

      # - name: Install Requirements
      #   run:  pip install flask flask-wtf coverage

      # - name: Unit Test
      #   run: |
      #     coverage run -m unittest -v test
      #     coverage xml -o cov/coverage.xml
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

      - name: Docker Login
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: | 
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev/
      - name: Build Image & Push
        env: 
          ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
        run: | 
          #Backend
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/myappbackend:latest ./kit-hackathon-aso/backend/
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/myappbackend:latest
          #Frontend
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/myappfrontend:latest ./kit-hackathon-aso/frontend/
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/myappfrontend:latest

  DeployProd:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Auth GCP
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy-backend'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'hello-cloud-run'
          image: '${{ secrets.ARTIFACT_REGISTRY }}/myappbackend:latest'
      
      - id: 'deploy-frontend'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'hello-cloud-run'
          image: '${{ secrets.ARTIFACT_REGISTRY }}/myappfrontend:latest'

      - name: 'Health check Backend'
        run: 'curl "${{ steps.deploy-frontend.outputs.url }}"'

      - name: Health check Frontend
        run: 'curl "${{ steps.deploy-backend.outputs.url }}"'